# train.py Config - Training
train:
  # For datasets, please pass atleast 1 value. If no datasets exist, pass "" as path for images.
  # Synthetic datasets with ground truth labels
  datasetsTrain:
      - images: '/scratch/s4304675/ai_master_thesis/cleargrasp-dataset-train/stemless-plastic-champagne-glass-train/rgb-imgs'
        labels: '/scratch/s4304675/ai_master_thesis/cleargrasp-dataset-train/stemless-plastic-champagne-glass-train/camera-normals'
      - images: '/scratch/s4304675/ai_master_thesis/cleargrasp-dataset-train/square-plastic-bottle-train/rgb-imgs'
        labels: '/scratch/s4304675/ai_master_thesis/cleargrasp-dataset-train/square-plastic-bottle-train/camera-normals'
      - images: '/scratch/s4304675/ai_master_thesis/cleargrasp-dataset-train/heart-bath-bomb-train/rgb-imgs'
        labels: '/scratch/s4304675/ai_master_thesis/cleargrasp-dataset-train/heart-bath-bomb-train/camera-normals'
      - images: '/scratch/s4304675/ai_master_thesis/cleargrasp-dataset-train/flower-bath-bomb-train/rgb-imgs'
        labels: '/scratch/s4304675/ai_master_thesis/cleargrasp-dataset-train/flower-bath-bomb-train/camera-normals'
      - images: '/scratch/s4304675/ai_master_thesis/cleargrasp-dataset-train/cup-with-waves-train/rgb-imgs'
        labels: '/scratch/s4304675/ai_master_thesis/cleargrasp-dataset-train/cup-with-waves-train/camera-normals'


  # Synthetic datasets with ground truth labels - 10% split of train
  datasetsVal:
      - images: '/scratch/s4304675/ai_master_thesis/cleargrasp-dataset-test-val/synthetic-val/stemless-plastic-champagne-glass-val/rgb-imgs'
        labels: '/scratch/s4304675/ai_master_thesis/cleargrasp-dataset-test-val/synthetic-val/stemless-plastic-champagne-glass-val/camera-normals'
      - images: '/scratch/s4304675/ai_master_thesis/cleargrasp-dataset-test-val/synthetic-val/square-plastic-bottle-val/rgb-imgs'
        labels: '/scratch/s4304675/ai_master_thesis/cleargrasp-dataset-test-val/synthetic-val/square-plastic-bottle-val/camera-normals'
      - images: '/scratch/s4304675/ai_master_thesis/cleargrasp-dataset-test-val/synthetic-val/heart-bath-bomb-val/rgb-imgs'
        labels: '/scratch/s4304675/ai_master_thesis/cleargrasp-dataset-test-val/synthetic-val/heart-bath-bomb-val/camera-normals'
      - images: '/scratch/s4304675/ai_master_thesis/cleargrasp-dataset-test-val/synthetic-val/flower-bath-bomb-val/rgb-imgs'
        labels: '/scratch/s4304675/ai_master_thesis/cleargrasp-dataset-test-val/synthetic-val/flower-bath-bomb-val/camera-normals'
      - images: '/scratch/s4304675/ai_master_thesis/cleargrasp-dataset-test-val/synthetic-val/cup-with-waves-val/rgb-imgs'
        labels: '/scratch/s4304675/ai_master_thesis/cleargrasp-dataset-test-val/synthetic-val/cup-with-waves-val/camera-normals'

  # Real Images (no ground truth labels)
  datasetsTestReal:
          #- images: 'data/datasets/real-test/d415/'
          #labels: ''
          #- images: 'data/datasets/real-test/d435/'
          #labels: ''
          #- images: 'data/datasets/real-val/d435/'
          #labels: ''

  # Synthetic datasets with ground truth labels - Used as test set
  datasetsTestSynthetic:
          #- images: 'data/cleargrasp-dataset-test-val/synthetic-test/glass-round-potion-test/rgb-imgs'
          #labels: 'data/cleargrasp-dataset-test-val/synthetic-test/glass-round-potion-test/camera-normals'
          #- images: 'data/cleargrasp-dataset-test-val/synthetic-test/glass-square-potion-test/rgb-imgs'
          #labels: 'data/cleargrasp-dataset-test-val/synthetic-test/glass-square-potion-test/camera-normals'
          #- images: 'data/cleargrasp-dataset-test-val/synthetic-test/star-bath-bomb-test/rgb-imgs'
          #labels: 'data/cleargrasp-dataset-test-val/synthetic-test/star-bath-bomb-test/camera-normals'
          #- images: 'data/cleargrasp-dataset-test-val/synthetic-test/tree-bath-bomb-test/rgb-imgs'
          #labels: 'data/cleargrasp-dataset-test-val/synthetic-test/tree-bath-bomb-test/camera-normals'

  # For pretraining surface normals on Matterport3D and Scannet Datasets
  datasetsMatterportTrain:
    # - images: 'data/datasets/matterport3d/train/matterport_rgb/v1/scans'
    #   labels: 'data/datasets/matterport3d/train/matterport_render_normal'
  datasetsMatterportVal:
    # - images: 'data/datasets/matterport3d/val/matterport_rgb/v1/scans'
    #   labels: 'data/datasets/matterport3d/val/matterport_render_normal'
  datasetsScannetTrain:
    # - images: 'data/datasets/scannet/scannet-rgb/scans/train'
    #   labels: 'data/datasets/scannet/scannet_render_normal/train'
  datasetsScannetVal:
    # - images: 'data/datasets/scannet/scannet-rgb/scans/val'
    #   labels: 'data/datasets/scannet/scannet_render_normal/val'


  # Training/Validation Params
  model: "drn_psa" # Possible values: ['deeplab_xception', 'deeplab_resnet', 'drn']
  batchSize: 16
  batchSizeMatterport: 0
  batchSizeScannet: 0
  validationBatchSize: 16
  testBatchSize: 16
  numEpochs: 10
  imgHeight: 256
  imgWidth: 256
  numClasses: 3
  numInputChannels: 3 # Num of channels in input image. RGB = 3 channels, Grayscale = 1 channel.
  numWorkers: 8 # Num of workers used in the dataloader
  logsDir: "/scratch/s4304675/ai_master_thesis/logs_drn_psa_set_2" # Directory where logs of each exp will be saved.
  lossFunc: "cosine" # Possible values: ['cosine', 'radians']
  percentageDataForTraining: 1.0 # The percentage of images in dataset to be used for training.
  percentageDataForValidation: 1.0

  # Deeplab specific
  outputStride: 8 # Possible values: [8, 16]. Output stride for deeplabv3 model. Smaller values give finer details in output mask.
  epochSize: 1 # After these many epochs, change learning rate

  continueTraining: True # If true, continue training from a checkpoint
  pathPrevCheckpoint: "/scratch/s4304675/ai_master_thesis/logs_drn_psa_set_2/surface_normals/exp-10/sur_normal_epoch_10.pth" # Path to .pth checkpoint file to load to continue training from
  initOptimizerFromCheckpoint: False # Re-Initialize optimizer's state from checkpoint. NOTE: when this is enabled, value of learningRate will be overridden with value from checkpoint.
  loadEpochNumberFromCheckpoint: False # If true, the epoch/iter numbering will start from the checkpoint's last epoch num.

  saveModelInterval: 2 # Save the model checkpoints every N epochs
  saveOptimizerState: 1

  # Optimizer Params
  optimAdam:
    learningRate: 0.0001
    weightDecay: 0 # Other values: 0.0001
  optimSgd:
    learningRate: 1.40e-4
    momentum: 0.9
    weight_decay: 5.0e-5
  lrScheduler: "PolyLR" # Possible Values: ['', 'StepLR', 'ReduceLROnPlateau', 'PolyLR'] 
  lrSchedulerStep:
    step_size: 7
    gamma: 0.1
  lrSchedulerPlateau:
    factor: 0.8
    patience: 25
    verbose: True
  lrSchedulerPoly:
    power: 0.25


# eval.py Config - Validation/Testing Inference
eval:
  # Synthetic datasets with ground truth labels
  # Used as validation set
  datasetsSynthetic:
    - images: 'data/data/datasets/val/cup-with-waves-val/source-files/rgb-imgs'
      labels: 'data/data/datasets/val/cup-with-waves-val/source-files/outlines'

  # Datasets of real images, no labels available
  # Used as Test set
  datasetsReal:
    # - images: "datasets-transparent/studio_pics_sorted/selected_test/d415"
    #   labels: "datasets-transparent/studio_pics_sorted/selected_test/d415"
    # - images: "datasets-transparent/studio_pics_sorted/selected_test/d435"
    #   labels: "datasets-transparent/studio_pics_sorted/selected_test/d435"
    # - images: "datasets-transparent/studio_pics_sorted/selected_val/d435"
    #   labels: "datasets-transparent/studio_pics_sorted/selected_val/d435"

  datasetsMatterport:
    # - images: 'data/datasets/matterport3d/train/matterport_rgb/v1/scans'
    #   labels: 'data/datasets/matterport3d/train/matterport_render_normal'

  # Params
  model: "drn" # Possible values: ['deeplab_xception', 'deeplab_resnet', 'drn']
  numClasses: 3
  batchSize: 32
  imgHeight: 256
  imgWidth: 256
  os: 8
  numWorkers: 4 # Num of workers used in the dataloader
  pathWeightsFile: "checkpoints/outlines/drn-256p-contact-edges/checkpoints/checkpoint-epoch-0051.pth" # Path to the checkpoint to be loaded
  resultsDir: "data/results"

